# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_picture_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
