# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 12:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160815_1134'),
    ]

    operations = [

    ]
